<a href="https://colab.research.google.com/github/Anamikarajesh/intro-to-deep-learning/blob/main/Backpropogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression

Self Implementation

In [130]:
import pandas as pd
import numpy as np

In [131]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [132]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [133]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameter={}
  L = len(layer_dims)
  for l in range(1,L):
    parameter['W'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameter['b'+str(l)] = np.zeros((layer_dims[l],1))
  return parameter

In [134]:
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T, A_prev) + b
  return Z

In [135]:
def L_layer_forward(X, parameters):
  A=X
  L=len(parameters)//2
  for l in range(1,L+1):
    A_prev = A
    W1 = parameters['W'+str(l)]
    b1 = parameters['b'+str(l)]
    #print("A"+str(l-1)+":",A_prev)
    #print("W"+str(l)+":",W1)
    #print("b"+str(l)+":",b1)
    #print("--"*20)
    A = linear_forward(A_prev,W1,b1)
    #print("A"+str(l)+":",A)
    #print("**"*20)
  return A,A_prev

In [136]:
def update_parameter(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001*2*(y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001*2*(y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.01*2*(y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001*2*(y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001*2*(y-y_hat)*parameters['W2'][1][0])
  return parameters

In [137]:
parameters= initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
  Loss = []
  for j in range(df.shape[0]):
    X = df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]
    update_parameter(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)
  print('Epoch -',i+1,'Loss -',np.array(Loss).mean())
parameters

Epoch - 1 Loss - 24.995222659678255
Epoch - 2 Loss - 16.17636229262528
Epoch - 3 Loss - 7.829721477782128
Epoch - 4 Loss - 2.87671424213171
Epoch - 5 Loss - 1.3691799500129394


{'W1': array([[0.24950607, 0.36066908],
        [0.26005464, 0.38076906]]),
 'b1': array([[0.0250078 ],
        [0.02686493]]),
 'W2': array([[0.38589297],
        [0.44810832]]),
 'b2': array([[1.09337986]])}

Using Keras

In [138]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [139]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [140]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [141]:
model.get_weights()

[array([[1.1806675 , 0.11786222],
        [0.73303735, 1.0853049 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.4068439],
        [ 0.4072926]], dtype=float32),
 array([0.], dtype=float32)]

In [142]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype = np.float32),
               np.array([0.,0.], dtype = np.float32),
               np.array([[0.1],[0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [143]:
model.set_weights(new_weights)

In [144]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [145]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [146]:
model.fit(df.iloc[:,:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 26.6830  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.6142 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31.2589 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 32.5859 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.1300
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 29.9922 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 27.4421 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25.7335
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 28.1107
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25.4082 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 27.2423 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 24.5545 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 24.9157 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 18.2961 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 25.3795
Epoch 16/7

In [147]:
model.get_weights()

[array([[0.3735534 , 0.3735534 ],
        [0.36546484, 0.36546484]], dtype=float32),
 array([0.27220434, 0.27220434], dtype=float32),
 array([[0.3728046],
        [0.3728046]], dtype=float32),
 array([0.2047138], dtype=float32)]

# Classification

Self Implementation

In [148]:
df_new = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa','profile_score','placed'])

In [149]:
df_new

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [150]:
def sigmoid(Z):
  A = 1/(1+np.exp(-Z))
  return A

In [151]:
def linear_forward_new(A_prev,W,b):
  Z = np.dot(W.T, A_prev) + b
  A = sigmoid(Z)
  return A

In [152]:
def update_parameter_new(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001*(y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001*(y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.0001*(y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001*(y-y_hat)*parameters['W2'][0][0]*A1[1][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[1][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001*(y-y_hat)*parameters['W2'][1][0]*A1[0][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))
  return parameters

In [153]:
parameter_new = initialize_parameters([2,2,1])
epochs = 50
for i in range(epochs):
  Loss_new = []
  for j in range(df_new.shape[0]):
    X_new = df_new[['cgpa','profile_score']].values[j].reshape(2,1)
    y_new = df_new['placed'].values[j]
    y_hat_new,A1_new = L_layer_forward(X_new,parameter_new)
    y_hat_new = y_hat_new[0][0]
    update_parameter_new(parameter_new,y_new,y_hat_new,A1_new,X_new)
    Loss_new.append(-(y_new*np.log(y_hat_new)+(1-y_new)*np.log(1-y_hat_new)))
    print('Epoch -',i+1,'Loss -',np.array(Loss_new).mean())
parameter_new

Epoch - 1 Loss - 1.1394342831883646
Epoch - 1 Loss - 1.1390479154545232
Epoch - 1 Loss - 0.8881618023461689
Epoch - 1 Loss - 0.7219929843605494
Epoch - 2 Loss - 1.1385167495209683
Epoch - 2 Loss - 1.138131769015664
Epoch - 2 Loss - 0.8876945183304428
Epoch - 2 Loss - 0.721709284557483
Epoch - 3 Loss - 1.1376037306990416
Epoch - 3 Loss - 1.1372201267059594
Epoch - 3 Loss - 0.8872297248585991
Epoch - 3 Loss - 0.7214272287838698
Epoch - 4 Loss - 1.1366951914384131
Epoch - 4 Loss - 1.1363129533442837
Epoch - 4 Loss - 0.8867674014940201
Epoch - 4 Loss - 0.7211468030580506
Epoch - 5 Loss - 1.1357910967952463
Epoch - 5 Loss - 1.135410214088763
Epoch - 5 Loss - 0.8863075280071312
Epoch - 5 Loss - 0.7208679935446046
Epoch - 6 Loss - 1.1348914121620575
Epoch - 6 Loss - 1.134511874432806
Epoch - 6 Loss - 0.8858500843728806
Epoch - 6 Loss - 0.7205907865525254
Epoch - 7 Loss - 1.1339961032637864
Epoch - 7 Loss - 1.133617900201188
Epoch - 7 Loss - 0.8853950507682528
Epoch - 7 Loss - 0.72031516853341

{'W1': array([[0.09622331, 0.09620489],
        [0.09622424, 0.09620561]]),
 'b1': array([[-0.00047394],
        [-0.0004739 ]]),
 'W2': array([[0.10699236],
        [0.10699182]]),
 'b2': array([[0.00406887]])}

Keras

In [154]:
model_new = Sequential()
model_new.add(Dense(2,activation='sigmoid',input_dim=2))
model_new.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [155]:
model_new.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [156]:
model_new.get_weights()

[array([[ 0.95045936,  0.9286934 ],
        [-0.19179356,  0.91441214]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0555857],
        [-1.3214638]], dtype=float32),
 array([0.], dtype=float32)]

In [157]:
model_new.set_weights(new_weights)

In [158]:
model_new.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [161]:
optimizer = keras.optimizers.Adam(learning_rate=0.0001)
model_new.compile(loss='binary_crossentropy',optimizer=optimizer)

In [162]:
model_new.fit(df_new.iloc[:,0:-1].values,df_new['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.6560
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.6715 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7138
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.7326 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6715
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7137 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7326
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.6837
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.6733
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7066
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.7026 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.6826 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.6734 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6716 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.7026 
Epoch 16/50
4/4 ━━━━━━━━━━